RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 700
CHUNK_OVERLAP: 60
DATA_PATH: "data/"
DB_FAISS_PATH: "vectorstore/db_faiss"
MODEL_TYPE: "mistral"
MODEL_BIN_PATH: "models/mistral-7b-instruct-v0.1.Q5_K_M.gguf"
EMBEDDINGS: "sentence-transformers/all-MiniLM-L6-v2"
MAX_NEW_TOKENS: 1048
TEMPERATURE: 0.00
